### ISSUE TITLE
Sticky label is not working as expected. 

### ISSUE THREAD

**Issue by Mahons** [dariopb/traefikServiceFabricPlugin#13]
Hi @dariopb , setting the sticky label within the SF application has no impact on the load balancer configuration. I got it working locally by initiating the internal Cookie struct within the Sticky struct. I will raise a PR to fix this issue along with implementing the additional Sticky labels, i.e., Name, HttpOnly, Secure, and SameSite.

Hi @ldez, one thing I noticed when configuring the Sticky session is that it's not displaying the fact that a service is configured with Sticky session within the dashboard. Is this expected behaviour? Note that I have validated that the cookie is being set within Postman, I've also confirmed that NTLM Auth is working which requires sticky sessions so I know it's turned on under the hood.

**Comment by nokjuh** [comment]
I made a pull request for this. Hopefully I didn't do too much overlapping work with @Mahons. Please let me know if the pull request needs to be improved, I am rather new at the process.

For me Traefik dashboard does show other sticky session cookie settings, except SameSite is not shown.
