### ISSUE TITLE
No label for customising entry point(s).

### ISSUE THREAD

**Issue by Mahons** [dariopb/traefikServiceFabricPlugin#7]
The current plugin, has hard coded the entry point as "web". We use different names for our entry point(s).

We also have a  requirement to expose some services through multiple entry points, i.e., public services vs internal services.

I've changed it locally and I'll submit a PR over the coming days.

**Comment by Mahons** [comment]
Hi @dariopb, I don't have write access to the repository. Would you be able to give me write access so I can create a PR?

**Comment by dariopb** [comment]
You should be able to send a PR from your branch already (not commit directly but create a branch and send a PR). I validated creating a new one from a different account.

**Comment by Mahons** [comment]
Hi @dariopb, I had created a separate branch and was trying t o publish it prior to create a PR. See error below:

![image](https://user-images.githubusercontent.com/5196617/140321962-8f330663-01d8-4f65-8d1b-2624f20a1bbe.png)

I've tried authenticating with both username/password and PAT to no avail. Do you need to give me any additional access rights on the repo?

**Comment by Mahons** [comment]
Hi @dariopb, once I forked it and pushed the branch to my own repository, I was able to create the PR here.
